version: "3.1"

# Replace secret_key:
# 11,$s/SECRET_KEY=""/SECRET_KEY=""
# 11,$s/SECRET_KEY="*.*"/SECRET_KEY=""
#
# Replace all the database credentials
# 9s/entity/<...>/g
# 11,$s/users:users@database\/base/entity:entity@database\/entity/g

services:
  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: users
      POSTGRES_PASSWORD: users
    command: [ "docker-entrypoint.sh", "-c", "wal_level=logical", "-c", "max_connections=300" ]

# {{{ messages
  messages_api:
    image: kennycallado/q-api-messages:latest
    ports:
      - "8005:8000"
    
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://users:users@database/messages"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - database
# }}}

# {{{ profiles - users - auth
  # {{{ profiles
  profiles_api:
    image: kennycallado/q-api-profiles:latest
    ports:
      - "8001:8000"
    
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://users:users@database/profiles"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - database
  # }}}
  
  # # {{{ users
  # users_api:
  #   image: kennycallado/q-api-users:latest
  #   ports:
  #     - "8002:8000"
  #   
  #   environment:
  #     - ROCKET_ADDRESS="0.0.0.0"
  #     - ROCKET_PORT=8000
  #     - ROCKET_SECRET_KEY=""
  #     - ROCKET_DATABASES={questions={url="postgres://users:users@database/users"}}

  #     - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
  #     - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
  #     - ROCKET_AUTH_URL="http://auth_api:8000/"
  #     - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
  #     - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
  #     - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
  #     - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
  #     - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
  #     - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
  #     - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
  #     - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
  #     - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
  #   depends_on:
  #     - database
  # # }}}

  # {{{ auth
  auth_api:
    image: kennycallado/q-api-auth:latest
    # extra_hosts:
    #   - "host.docker.internal:host-gateway" # seems doesn't work
    ports:
      - "8003:8000"
    
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      # - ROCKET_USER_URL="http://host.docker.internal:8000/api/v1/user/"
    depends_on:
      - database
  # }}}
# }}}

# {{{ questions - answers
  # {{{ questions
  questions_api:
    image: kennycallado/q-api-questions:latest
    ports:
      - "8011:8000"
    
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://users:users@database/questions"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - database
  # }}}

  # {{{ answers
  answers_api:
    image: kennycallado/q-api-answers:latest
    ports:
      - "8012:8000"
    
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://users:users@database/answers"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - database
      - questions_api
  # }}}
# }}}

# {{{ slides
  # {{{ slides
  slides_api:
    image: kennycallado/q-api-slides:latest
    ports:
      - "8021:8000"
    
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://users:users@database/slides"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - database
      - questions_api
  # }}}
# }}}

# {{{ resources - papers
  # {{{ resources
  resources_api:
    image: kennycallado/q-api-resources:latest
    ports:
      - "8031:8000"
    
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://users:users@database/resources"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - database
      - slides_api
  # }}}
  
  # {{{ papers
  papers_api:
    image: kennycallado/q-api-papers:latest
    ports:
      - "8032:8000"
    
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://users:users@database/papers"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - database
      - resources_api
  # }}}
# }}}

# {{{ checker - logics
  # {{{ checker
  checker_api:
    image: kennycallado/q-api-checker:latest
    ports:
      - "3000:3000"
    
    volumes:
      - scripts:/app/SCRIPTS
  # }}}
  
  # {{{ logics and logics-cron
  logics_api:
    image: kennycallado/q-api-logics:latest
    ports:
      - "8041:8000"
    
    volumes:
      - scripts:/root/SCRIPTS
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      # - ROCKET_DATABASES={questions={url="postgres://users:users@database/logics"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - database
      - checker_api
      - projects_api

  logics-cron_api:
    image: kennycallado/q-api-logics:latest
    volumes:
      - scripts:/root/SCRIPTS
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      # - ROCKET_DATABASES={questions={url="postgres://users:users@database/logicscron"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - database
      - checker_api
      - projects_api
  # }}}
# }}}

# {{{ projects - cron
  # {{{ projects
  projects_api:
    image: kennycallado/q-api-projects:latest
    ports:
      - "8051:8000"
    
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://users:users@database/projects"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - database
  # }}}

  # {{{ cron
  cron_api:
    image: kennycallado/q-api-cron:latest
    ports:
      - "8052:8000"
    
    environment:
      - ROCKET_ADDRESS="0.0.0.0"
      - ROCKET_PORT=8000
      - ROCKET_SECRET_KEY=""
      - ROCKET_DATABASES={questions={url="postgres://users:users@database/cron"}}

      - ROCKET_PROFILE_URL="http://profiles_api:8000/api/v1/profile/"
      - ROCKET_USER_URL="http://users_api:8000/api/v1/user/"
      - ROCKET_AUTH_URL="http://auth_api:8000/"
      - ROCKET_MESSAGE_URL="http://messages_api:8000/api/v1/messaging/"
      - ROCKET_QUESTION_URL="http://questions_api:8000/api/v1/question/"
      - ROCKET_ANSWER_URL="http://answers_api:8000/api/v1/answer/"
      - ROCKET_SLIDE_URL="http://slides_api:8000/api/v1/slide/"
      - ROCKET_RESOURCE_URL="http://resources_api:8000/api/v1/resource/"
      - ROCKET_PAPER_URL="http://papers_api:8000/api/v1/paper/"
      - ROCKET_LOGIC_URL="http://logics-cron_api:8000/api/v1/logic/"
      # - ROCKET_LOGIC_URL="http://logics_api:8000/api/v1/logic/"
      - ROCKET_CHECKER_URL="http://checker_api:3000/api/v1/checker/"
      - ROCKET_PROJECT_URL="http://projects_api:8000/api/v1/project/"
    depends_on:
      - database
      - logics_api
  # }}}
# }}}

volumes:
  scripts:
